-- ME ADD PRO STATUS TO MAIN TRIBE CAVE (ORGANIZATIONS)
ALTER TABLE organizations ADD COLUMN IF NOT EXISTS is_pro BOOLEAN DEFAULT FALSE;

-- NEW CAVE TO HOLD MAGIC STICKS (PROMOTIONAL CODES)
CREATE TABLE promotional_codes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT UNIQUE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    max_uses INTEGER NOT NULL DEFAULT 1,
    current_uses INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- TALLY ROCK (AUDIT TABLE) TO KNOW WHO TOOK MAGIC STICK
CREATE TABLE code_redemptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id UUID NOT NULL REFERENCES organizations(id),
    code_id UUID NOT NULL REFERENCES promotional_codes(id),
    redeemed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- PUT HEAVY ROCK DOORS (RLS) ON NEW TABLES
ALTER TABLE promotional_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE promotional_codes FORCE ROW LEVEL SECURITY;

ALTER TABLE code_redemptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE code_redemptions FORCE ROW LEVEL SECURITY;

-- ANYONE CAN TRY TO READ MAGIC STICKS (BUT MUST GUESS STRING TO FIND IT)
-- BACKEND WILL HANDLE THE UPDATE SAFELY
CREATE POLICY read_promo_code ON promotional_codes FOR SELECT USING (true);
CREATE POLICY update_promo_code ON promotional_codes FOR UPDATE USING (true);

-- TENANT CAN ONLY SEE THEIR OWN REDEMPTIONS
CREATE POLICY tenant_isolation_redemptions ON code_redemptions FOR ALL
USING (org_id = COALESCE(NULLIF(current_setting('app.tenant_id', true), ''), '00000000-0000-0000-0000-000000000000')::uuid);
